### ISSUE TITLE
git remotes for repositories should be updated

### ISSUE THREAD

**Issue by spencerbywater-wf** [ryanhanks-wf/bam_workspace#26]
If you run `git remote -v` on some of the repositories, the origin for some of them points to out-of-date repositories.
Specifically:
| Branch | Current Origin | Should be updated to |
| --- | --- | --- |
| books | git@github.com:ryanhanks-wf/books.git | git@github.com:workiva/books.git |
| wf-mobile-services | git@github.com:ericdebusschere-wf/wf-mobile-services.git | git@github.com:workiva/wf-mobile-services.git |

**Comment by maxwellclarke-wf** [comment]
Fixed: https://github.com/ryanhanks-wf/bam_workspace/blob/master/Makefile#L8
